{"uuid": "d57a2e83-3089-43c7-9cc8-4bbaa670f1a6", "children": ["d9011aaf-4837-4899-a5eb-fd4d824c5ce2"], "befores": [{"name": "driver", "status": "passed", "start": 1713813990918, "stop": 1713813993513}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: module 'datetime' has no attribute 'today'\n", "trace": "  File \"/Users/sergeykazakov/PycharmProjects/python_redrover/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/sergeykazakov/PycharmProjects/python_redrover/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/sergeykazakov/PycharmProjects/python_redrover/conftest.py\", line 20, in driver\n    allure.attach(attach, name=f\"Screenshot {datetime.today}\", attachment_type=allure.attachment_type.PNG)\n                                             ^^^^^^^^^^^^^^\n"}, "start": 1713813994291, "stop": 1713813995170}], "start": 1713813990918, "stop": 1713813995170}