{"uuid": "6077fc54-b7e2-4445-983f-22567a7a0b10", "children": ["8718b806-7c00-4d55-8a1d-64c1810998f3"], "befores": [{"name": "driver", "status": "passed", "start": 1713813987134, "stop": 1713813989096}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: module 'datetime' has no attribute 'today'\n", "trace": "  File \"/Users/sergeykazakov/PycharmProjects/python_redrover/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/sergeykazakov/PycharmProjects/python_redrover/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/sergeykazakov/PycharmProjects/python_redrover/conftest.py\", line 20, in driver\n    allure.attach(attach, name=f\"Screenshot {datetime.today}\", attachment_type=allure.attachment_type.PNG)\n                                             ^^^^^^^^^^^^^^\n"}, "start": 1713813990386, "stop": 1713813990886}], "start": 1713813987134, "stop": 1713813990886}